# Generated by Django 2.1.4 on 2019-02-06 14:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0070_interface_vxlan'),
        ('taggit', '0002_auto_20150616_2121'),
        ('tenancy', '0009_remove_tenant_vxlan_prefix'),
        ('ipam', '0024_auto_20190122_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='VxLAN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('vni', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1677)])),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'VxLAN',
                'verbose_name_plural': 'VxLANs',
                'ordering': ['site', 'group', 'vni'],
            },
        ),
        migrations.CreateModel(
            name='VxLANGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vxlan_groups', to='dcim.Site')),
            ],
            options={
                'verbose_name': 'VxLAN group',
                'verbose_name_plural': 'VxLAN groups',
                'ordering': ['site', 'name'],
            },
        ),
        migrations.AddField(
            model_name='vxlan',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vxlans', to='ipam.VxLANGroup'),
        ),
        migrations.AddField(
            model_name='vxlan',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vxlans', to='ipam.Role'),
        ),
        migrations.AddField(
            model_name='vxlan',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vxlans', to='dcim.Site'),
        ),
        migrations.AddField(
            model_name='vxlan',
            name='tags',
            field=taggit.managers.TaggableManager(through='taggit.TaggedItem', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='vxlan',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vxlans', to='tenancy.Tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='vxlangroup',
            unique_together={('site', 'slug'), ('site', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='vxlan',
            unique_together={('group', 'name'), ('group', 'vni')},
        ),
    ]
