# Generated by Django 2.1.4 on 2019-02-14 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0025_auto_20190206_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan',
            name='vxlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vlans', to='ipam.VxLAN'),
        ),
    ]
