# Generated by Django 2.1.4 on 2019-02-14 13:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0075_remove_interface_vxlan'),
        ('taggit', '0002_auto_20150616_2121'),
        ('tenancy', '0009_remove_tenant_vxlan_prefix'),
        ('ipam', '0026_vlan_vxlan'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverlayNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('vni', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1677)])),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'OverlayNetwork',
                'verbose_name_plural': 'OverlayNetworks',
                'ordering': ['site', 'group', 'vni'],
            },
        ),
        migrations.CreateModel(
            name='OverlayNetworkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overlay_network_groups', to='dcim.Site')),
            ],
            options={
                'verbose_name': 'OverlayNetwork group',
                'verbose_name_plural': 'OverlayNetwork groups',
                'ordering': ['site', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='vxlan',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vxlan',
            name='group',
        ),
        migrations.RemoveField(
            model_name='vxlan',
            name='role',
        ),
        migrations.RemoveField(
            model_name='vxlan',
            name='site',
        ),
        migrations.RemoveField(
            model_name='vxlan',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='vxlan',
            name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='vxlangroup',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vxlangroup',
            name='site',
        ),
        migrations.RemoveField(
            model_name='vlan',
            name='vxlan',
        ),
        migrations.DeleteModel(
            name='VxLAN',
        ),
        migrations.DeleteModel(
            name='VxLANGroup',
        ),
        migrations.AddField(
            model_name='overlaynetwork',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overlay_networks', to='ipam.OverlayNetworkGroup'),
        ),
        migrations.AddField(
            model_name='overlaynetwork',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overlay_networks', to='ipam.Role'),
        ),
        migrations.AddField(
            model_name='overlaynetwork',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overlay_networks', to='dcim.Site'),
        ),
        migrations.AddField(
            model_name='overlaynetwork',
            name='tags',
            field=taggit.managers.TaggableManager(through='taggit.TaggedItem', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='overlaynetwork',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overlay_networks', to='tenancy.Tenant'),
        ),
        migrations.AddField(
            model_name='vlan',
            name='overlay_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vlans', to='ipam.OverlayNetwork'),
        ),
        migrations.AlterUniqueTogether(
            name='overlaynetworkgroup',
            unique_together={('site', 'slug'), ('site', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='overlaynetwork',
            unique_together={('group', 'vni'), ('group', 'name')},
        ),
    ]
