# Generated by Django 2.1.4 on 2019-04-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0028_auto_20190214_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrf',
            name='imports',
            field=models.ManyToManyField(blank=True, related_name='imported', to='ipam.VRF'),
        ),
    ]
