# Generated by Django 2.2.6 on 2019-10-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0027_ipaddress_add_dns_name'),
        ('ipam', '0029_vrf_imports'),
    ]

    operations = [
    ]
