# Generated by Django 2.2.6 on 2019-12-06 10:02

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0030_merge_20191002_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overlaynetwork',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]
