# Generated by Django 2.2.8 on 2020-01-07 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0031_auto_20191206_1002'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vlan',
            unique_together={('group', 'vid'), ('overlay_network', 'vid'), ('group', 'name')},
        ),
    ]
