# Generated by Django 3.0.5 on 2020-04-16 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0032_auto_20200107_1031'),
        ('ipam', '0036_standardize_description'),
    ]

    operations = [
    ]
