# Generated by Django 3.1 on 2020-12-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0037_merge_20200416_0717'),
        ('ipam', '0037_ipaddress_assignment'),
    ]

    operations = [
    ]
