# Generated by Django 3.1 on 2020-12-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0038_merge_20201209_1142'),
        ('ipam', '0043_add_tenancy_to_aggregates'),
    ]

    operations = [
    ]
