# Generated by Django 2.0.9 on 2018-11-13 12:44

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectedCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_business', models.BooleanField()),
                ('products_affected', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ChangedField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('changed_object_id', models.PositiveIntegerField()),
                ('field', models.CharField(max_length=40)),
                ('old_value', models.CharField(max_length=150, null=True)),
                ('new_value', models.CharField(max_length=150, null=True)),
                ('changed_object_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='ChangedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('changed_object_id', models.PositiveIntegerField()),
                ('changed_object_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('changed_object_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_emergency', models.BooleanField()),
                ('affects_customer', models.BooleanField()),
                ('change_implications', models.TextField()),
                ('ignore_implications', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChangeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField(null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Draft'), (2, 'Under Review'), (3, 'Accepted'), (4, 'Implemented')], default=1)),
                ('change_information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='information', to='change.ChangeInformation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='changedobject',
            name='changeset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='change.ChangeSet'),
        ),
        migrations.AddField(
            model_name='changedobject',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changedfield',
            name='changeset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='change.ChangeSet'),
        ),
        migrations.AddField(
            model_name='changedfield',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affectedcustomer',
            name='information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='change.ChangeInformation'),
        ),
    ]
