# Generated by Django 2.0.9 on 2018-11-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectedcustomer',
            name='is_business',
            field=models.BooleanField(verbose_name='Is a business customer'),
        ),
        migrations.AlterField(
            model_name='affectedcustomer',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='affectedcustomer',
            name='products_affected',
            field=models.CharField(max_length=128, verbose_name='Affected Products'),
        ),
        migrations.AlterField(
            model_name='changeinformation',
            name='affects_customer',
            field=models.BooleanField(verbose_name='Customers are affected'),
        ),
        migrations.AlterField(
            model_name='changeinformation',
            name='is_emergency',
            field=models.BooleanField(verbose_name='Is an emergency change'),
        ),
    ]
