# Generated by Django 2.0.9 on 2018-10-15 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0001_create_changedfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='changedfield',
            name='changeset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='change.ChangeSet'),
        ),
    ]
