# Generated by Django 2.0.9 on 2018-11-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectedcustomer',
            name='is_business',
            field=models.BooleanField(verbose_name='Is a business customer'),
        ),
        migrations.AlterField(
            model_name='affectedcustomer',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='affectedcustomer',
            name='products_affected',
            field=models.CharField(max_length=128, verbose_name='Affected Products'),
        ),
        migrations.AlterField(
            model_name='changeinformation',
            name='affects_customer',
            field=models.BooleanField(verbose_name='Customers are affected'),
        ),
        migrations.AlterField(
            model_name='changeinformation',
            name='is_emergency',
            field=models.BooleanField(verbose_name='Is an emergency change'),
        ),
        migrations.AlterField(
            model_name='changeinformation',
            name='Art',
            field=models.BooleanField(verbose_name='Netzwerk-Change'),
        ),
#        migrations.AlterField(
#            model_name='changeinformation',
#            name='Art',
#            field=models.SmallIntegerField(choices=[(1, 'Standard Change (vorabgenehmigt)')], default=1),
#        ),
#        migrations.AlterField(
#            model_name='changeinformation',
#            name='Kategorie',
#            field=models.SmallIntegerField(choices=[(1, 'Netzwerk')], default=1),
#        ),
#        migrations.AlterField(
#            model_name='changeinformation',
#            name='Unterkategorie',
#            field=models.SmallIntegerField(choices=[(0, '------------'), (1, 'Routing/Switching'), (2, 'Firewall'), (3, 'CPE'), (4, 'Access Netz'), (5, 'Extern')], default=0),
#        ),
    ]
