# Generated by Django 2.0.9 on 2018-10-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0002_auto_20181015_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Under Review'), (1, 'Accepted'), (2, 'Implemented')], default=0),
        ),
    ]
