# Generated by Django 2.0.9 on 2018-11-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0003_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='user',
        ),
        migrations.AddField(
            model_name='changeset',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Change',
        ),
    ]
