# Generated by Django 2.0.9 on 2018-10-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0003_changeset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeset',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Under Review'), (2, 'Accepted'), (3, 'Implemented')], default=0),
        ),
    ]
