
# Generated by Django 2.0.9 on 2018-10-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0004_auto_20181015_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeset',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Draft'), (2, 'Under Review'), (3, 'Accepted'), (4, 'Implemented')], default=1),
        ),
    ]
