# Generated by Django 2.0.9 on 2018-11-30 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0004_auto_20181129_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
