# Generated by Django 2.0.9 on 2018-12-12 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0006_changeinformation_is_extensive'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
