# Generated by Django 2.0.9 on 2018-11-12 13:39

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('change', '0006_changedobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='changedobject',
            name='changed_object_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AddField(
            model_name='changeset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
