# Generated by Django 2.1.4 on 2019-01-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0007_changeset_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changedobject',
            name='changed_object_data',
        ),
    ]
