# Generated by Django 2.1.4 on 2019-01-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0008_auto_20190131_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='changedobject',
            name='changed_object_data',
            field=models.BinaryField(default=(b'')),
            preserve_default=False,
        ),
    ]
