# Generated by Django 2.1.4 on 2019-01-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0009_changedobject_changed_object_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changedfield',
            name='new_value',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='changedfield',
            name='old_value',
            field=models.BinaryField(null=True),
        ),
    ]
