# Generated by Django 2.1.4 on 2019-03-04 14:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0010_auto_20190131_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='provision_log',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
