# Generated by Django 2.1.4 on 2019-06-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0011_changeset_provision_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeinformation',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
