# Generated by Django 2.1.4 on 2019-06-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0012_changeinformation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='changedobject',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
