# Generated by Django 2.1.4 on 2019-08-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0013_changedobject_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeinformation',
            name='Art',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='changeinformation',
            name='Kategorie',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='changeinformation',
            name='Unterkategorie',
            field=models.SmallIntegerField(default=0),
        ),
    ]
