# Generated by Django 2.1.4 on 2019-08-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0014_auto_20190826_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changeinformation',
            old_name='Kategorie',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='changeinformation',
            old_name='Art',
            new_name='change_type',
        ),
        migrations.RenameField(
            model_name='changeinformation',
            old_name='Unterkategorie',
            new_name='subcategory',
        ),
    ]
