# Generated by Django 2.1.4 on 2019-09-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0015_auto_20190828_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeset',
            name='ticket_id',
        ),
        migrations.AddField(
            model_name='changeinformation',
            name='depends_on',
            field=models.ManyToManyField(related_name='dependants', to='change.ChangeSet'),
        ),
    ]
