# Generated by Django 2.2.6 on 2019-10-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0016_auto_20190930_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeinformation',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='dependants', to='change.ChangeSet'),
        ),
    ]
