# Generated by Django 2.2.6 on 2019-10-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0017_auto_20191008_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='mr_location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
