# Generated by Django 2.2.6 on 2020-02-04 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('change', '0018_changeset_mr_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('output_log_file', models.CharField(blank=True, max_length=512, null=True)),
                ('output_log', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='changeset',
            options={'permissions': [('deploy_changeset', 'Can deploy Changesets')]},
        ),
        migrations.RemoveField(
            model_name='changeinformation',
            name='affects_customer',
        ),
        migrations.RemoveField(
            model_name='changeinformation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='changeinformation',
            name='change_implications',
        ),
        migrations.RemoveField(
            model_name='changeinformation',
            name='change_type',
        ),
        migrations.RemoveField(
            model_name='changeinformation',
            name='depends_on',
        ),
        migrations.RemoveField(
            model_name='changeinformation',
            name='ignore_implications',
        ),
        migrations.RemoveField(
            model_name='changeinformation',
            name='is_emergency',
        ),
        migrations.RemoveField(
            model_name='changeinformation',
            name='is_extensive',
        ),
        migrations.RemoveField(
            model_name='changeinformation',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='changeinformation',
            name='topdesk_change_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changesets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AffectedCustomer',
        ),
        migrations.AddField(
            model_name='changeset',
            name='provision_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changesets', to='change.ProvisionSet'),
        ),
    ]
