# Generated by Django 2.2.6 on 2020-01-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0018_changeset_mr_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changeset',
            options={'permissions': [('deploy_changeset', 'Can deploy Changesets')]},
        ),
    ]
