# Generated by Django 2.2.6 on 2020-01-24 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0020_auto_20200123_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionset',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='provisionset',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changesets', to=settings.AUTH_USER_MODEL),
        ),
    ]
