# Generated by Django 2.2.9 on 2020-01-23 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0020_auto_20200123_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionset',
            name='error_log',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='provisionset',
            name='output_log',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
