# Generated by Django 2.2.9 on 2020-01-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0021_auto_20200123_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionset',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
