# Generated by Django 2.2.6 on 2020-01-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0021_auto_20200124_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeinformation',
            name='affects_customer',
        ),
        migrations.DeleteModel(
            name='AffectedCustomer',
        ),
    ]
