# Generated by Django 2.2.9 on 2020-01-28 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0022_provisionset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionset',
            name='pid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changesets', to=settings.AUTH_USER_MODEL),
        ),
    ]
