# Generated by Django 2.2.6 on 2020-01-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0023_remove_changeinformation_depends_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeinformation',
            name='topdesk_change_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
