# Generated by Django 2.2.6 on 2020-01-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0024_changeinformation_topdesk_change_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeinformation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='changeinformation',
            name='change_implications',
        ),
        migrations.RemoveField(
            model_name='changeinformation',
            name='change_type',
        ),
        migrations.RemoveField(
            model_name='changeinformation',
            name='ignore_implications',
        ),
        migrations.RemoveField(
            model_name='changeinformation',
            name='is_emergency',
        ),
        migrations.RemoveField(
            model_name='changeinformation',
            name='is_extensive',
        ),
        migrations.RemoveField(
            model_name='changeinformation',
            name='subcategory',
        ),
    ]
