# Generated by Django 2.2.6 on 2020-01-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0022_provisionset_status'),
        ('change', '0025_auto_20200124_1311'),
    ]

    operations = [
    ]
