# Generated by Django 2.2.6 on 2020-01-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0026_merge_20200128_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provisionset',
            old_name='output_log',
            new_name='output_log_file',
        ),
    ]
