# Generated by Django 2.2.6 on 2020-01-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0027_auto_20200131_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provisionset',
            name='error_log',
        ),
        migrations.AddField(
            model_name='provisionset',
            name='output_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
