# Generated by Django 2.2.6 on 2020-02-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0028_auto_20200131_1338'),
        ('change', '0023_auto_20200128_1249'),
    ]

    operations = [
    ]
