# Generated by Django 2.2.6 on 2020-02-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0029_merge_20200204_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provisionset',
            name='pid',
        ),
    ]
