# Generated by Django 2.2.10 on 2020-02-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0030_remove_provisionset_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeset',
            name='mr_location',
        ),
        migrations.RemoveField(
            model_name='changeset',
            name='provision_log',
        ),
        migrations.AddField(
            model_name='changeinformation',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='provisionset',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
