# Generated by Django 2.2.10 on 2020-03-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0031_auto_20200211_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeinformation',
            name='topdesk_change_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
