# Generated by Django 3.0.8 on 2020-08-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0033_auto_20200813_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provisionset',
            old_name='output_log',
            new_name='prepare_log',
        ),
        migrations.RenameField(
            model_name='provisionset',
            old_name='status',
            new_name='state',
        ),
    ]
