# Generated by Django 3.0.8 on 2020-08-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0034_auto_20200825_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionset',
            name='commit_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
