# Generated by Django 3.0.9 on 2020-09-02 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0035_provisionset_commit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeset',
            name='provision_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changesets', to='change.ProvisionSet'),
        ),
    ]
