# Generated by Django 3.0.9 on 2020-10-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0037_provisionset_odin_output'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provisionset',
            options={'permissions': [('rollback_last_provisionset', 'Can rollback the last ProvisionSet.'), ('rollback_any_provisionset', 'Can rollback all ProvisionSets.')]},
        ),
        migrations.AddField(
            model_name='changeset',
            name='reverted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provisionset',
            name='reverted',
            field=models.BooleanField(default=False),
        ),
    ]
