# Configuration for Stale (https://github.com/apps/stale)

# Pull requests are exempt from being marked as stale
only: issues

# Number of days of inactivity before an issue becomes stale
daysUntilStale: 14

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7

# Issues with these labels will never be considered stale
exemptLabels:
  - "status: accepted"
  - "status: gathering feedback"
  - "status: blocked"

# Label to use when marking an issue as stale
staleLabel: wontfix

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. NetBox
  is governed by a small group of core maintainers which means not all opened
  issues may receive direct feedback. Please see our [contributing guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md).

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been automatically closed due to lack of activity. In an
  effort to reduce noise, please do not comment any further. Note that the
  core maintainers may elect to reopen this issue at a later date if deemed
  necessary.
