version: '2'

services:
  db:
    environment:
      POSTGRES_DB: netbox
      POSTGRES_USER: netbox
      POSTGRES_PASSWORD: netbox
    restart: always
    image: postgres:9.6
    expose:
      - "5432"
  gitlab:
    restart: always
    image: gitlab/gitlab-ce
    expose:
      - "80"
    ports:
      - "8080:80"
    ports:
      - "8022:22"
  app:
    environment:
      DATABASE_URL: postgres://netbox:netbox@db/netbox
      DJANGO_MANAGEPY_MIGRATE: 'on'
      DJANGO_MANAGEPY_COLLECTSTATIC: 'on'
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
    links:
      - db:db
    ports:
      - "8000:8000"
