version: '3.2'

services:
  db:
    environment:
      POSTGRES_DB: netbox
      POSTGRES_USER: netbox
      POSTGRES_PASSWORD: netbox
    restart: always
    image: postgres:9.6
    ports:
      - "5432:5432"
    expose:
      - "5432"
  app:
    environment:
      DATABASE_URL: postgres://netbox:netbox@db/netbox
      DJANGO_MANAGEPY_MIGRATE: 'on'
      DJANGO_MANAGEPY_COLLECTSTATIC: 'on'
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db:db
    volumes:
      - netbox-sync:/code:nocopy
    ports:
      - "8000:8000"
volumes:
  netbox-sync:
    external: true
