version: '3.2'

services:
  db:
    environment:
      POSTGRES_DB: netbox
      POSTGRES_USER: netbox
      POSTGRES_PASSWORD: netbox
    restart: always
    image: postgres:9.6
    ports:
      - "5432:5432"
    expose:
      - "5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    expose:
      - "6379"
