version: '3.4'
services:
  netbox: &netbox
    image: gitlab.service.wobcom.de:5050/infrastructure/netbox:latest
    depends_on:
    - postgres
    - redis
    - redis-cache
    - netbox-worker
    - odin-service
    env_file: env/netbox.env
    user: '101'
    volumes:
    - ./configuration:/etc/netbox/config:z,ro
    - ./reports:/etc/netbox/reports:z,ro
    - ./scripts:/etc/netbox/scripts:z,ro
    - netbox-nginx-config:/etc/netbox-nginx:z
    - netbox-static-files:/opt/netbox/static:z
    - netbox-media-files:/opt/netbox/m/edia:z
  netbox-worker:
    <<: *netbox
    depends_on:
    - redis
    entrypoint:
    - python3
    - /opt/netbox/manage.py
    command:
    - rqworker
  nginx:
    command: nginx -c /etc/netbox-nginx/nginx.conf
    image: nginx:1.17-alpine
    depends_on:
    - netbox
    ports:
    - 8000:8080
    volumes:
    - netbox-static-files:/opt/netbox/static:ro
    - netbox-nginx-config:/etc/netbox-nginx/:ro
  postgres:
    image: postgres:11-alpine
    env_file: env/postgres.env
    volumes:
    - netbox-postgres-data:/var/lib/postgresql/data
  odin-service:
    image: registry.gitlab.com/wobcom/odin:latest
    depends_on:
    - postgres
    env_file: env/odin.env
    command: ["--netbox-host", "netbox", "--netbox-port", "8002", "--listen-port", "8001"]
    volumes:
      - ./odin-secrets:/secrets
  redis:
    image: redis:5-alpine
    volumes:
    - netbox-redis-data:/data
  redis-cache:
    image: redis:5-alpine
    env_file: env/redis-cache.env
volumes:
  netbox-static-files:
    driver: local
  netbox-nginx-config:
    driver: local
  netbox-media-files:
    driver: local
  netbox-postgres-data:
    driver: local
  netbox-redis-data:
    driver: local
