# Generated by Django 2.1.4 on 2019-03-19 08:43

import django.core.validators
from django.db import migrations, models
import ipam.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BGPConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('neighbor', ipam.fields.IPAddressField()),
                ('remote_as', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(65536)])),
            ],
        ),
    ]
