# Generated by Django 2.1.4 on 2019-03-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0076_interface_overlay_network'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bgpconfiguration',
            options={'verbose_name': 'BGP Configuration'},
        ),
        migrations.AddField(
            model_name='bgpconfiguration',
            name='devices',
            field=models.ManyToManyField(to='dcim.Device'),
        ),
    ]
