# Generated by Django 2.1.4 on 2019-03-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20190320_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgpconfiguration',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
