# Generated by Django 2.1.4 on 2019-03-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_auto_20190329_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bgpsession',
            old_name='session',
            new_name='community',
        ),
    ]
