# Generated by Django 2.1.4 on 2019-03-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_auto_20190329_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bgpcommunity',
            options={'verbose_name': 'BGP Community', 'verbose_name_plural': 'BGP Communities'},
        ),
        migrations.AlterField(
            model_name='bgpcommunity',
            name='community',
            field=models.CharField(max_length=128),
        ),
    ]
