# Generated by Django 2.1.4 on 2019-04-01 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0076_interface_overlay_network'),
        ('configuration', '0006_auto_20190331_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgpsession',
            name='device_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bgp_sessions_a', to='dcim.Device'),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='device_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bgp_sessions_b', to='dcim.Device'),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='tag',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bgpsession',
            name='devices',
            field=models.ManyToManyField(related_name='bgp_sessions', to='dcim.Device'),
        ),
    ]
