# Generated by Django 2.1.4 on 2019-04-01 12:02

import django.core.validators
from django.db import migrations, models
import ipam.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_auto_20190401_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgpsession',
            name='community',
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='communities',
            field=models.ManyToManyField(related_name='sessions', to='configuration.BGPCommunity'),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='device_a_as',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(65536)]),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='device_b_as',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(65536)]),
        ),
        migrations.AlterField(
            model_name='bgpsession',
            name='neighbor',
            field=ipam.fields.IPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bgpsession',
            name='remote_as',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(65536)]),
        ),
    ]
