# Generated by Django 2.1.4 on 2019-04-05 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0028_auto_20190214_1353'),
        ('configuration', '0008_auto_20190401_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgpsession',
            name='vrf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bgp_sessions', to='ipam.VRF'),
        ),
    ]
