# Generated by Django 2.1.4 on 2019-04-05 14:27

import django.core.validators
from django.db import migrations, models
import ipam.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_bgpsession_vrf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bgpsession',
            old_name='neighbor',
            new_name='neighbor_a',
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='neighbor_b',
            field=ipam.fields.IPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bgpsession',
            name='device_a_as',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4294967294)]),
        ),
        migrations.AlterField(
            model_name='bgpsession',
            name='remote_as',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4294967294)]),
        ),
    ]
