# Generated by Django 2.1.4 on 2019-04-08 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0028_auto_20190214_1353'),
        ('configuration', '0009_bgpsession_vrf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bgpsession',
            old_name='device_a_as',
            new_name='neighbor_a_as',
        ),
        migrations.RenameField(
            model_name='bgpsession',
            old_name='device_b_as',
            new_name='neighbor_b_as',
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='device_a',
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='device_b',
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='neighbor_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bgp_sessions_a', to='ipam.IPAddress'),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='neighbor_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bgp_sessions_b', to='ipam.IPAddress'),
        ),
    ]
