# Generated by Django 2.1.4 on 2019-04-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0010_auto_20190405_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgpsession',
            name='device_a_as',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bgpsession',
            name='device_b_as',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
