# Generated by Django 2.1.4 on 2019-04-23 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0011_auto_20190405_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgpsession',
            name='device_a_as',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4294967296)]),
        ),
        migrations.AlterField(
            model_name='bgpsession',
            name='device_b_as',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4294967296)]),
        ),
    ]
