# Generated by Django 2.1.4 on 2019-04-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0013_auto_20190423_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgpsession',
            name='communities',
            field=models.ManyToManyField(blank=True, null=True, related_name='sessions', to='configuration.BGPCommunity'),
        ),
    ]
