# Generated by Django 2.1.4 on 2019-04-24 10:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0077_devicelicense'),
        ('configuration', '0014_auto_20190423_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgpsession',
            name='device_a',
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='device_a_as',
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='device_b',
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='device_b_as',
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='devices',
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='interface_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bgp_sessions_a', to='dcim.Interface'),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='interface_a_as',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4294967296)]),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='interface_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bgp_sessions_b', to='dcim.Interface'),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='interface_b_as',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4294967296)]),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='interfaces',
            field=models.ManyToManyField(related_name='bgp_sessions', to='dcim.Interface'),
        ),
    ]
