# Generated by Django 2.1.4 on 2019-04-26 10:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0029_vrf_imports'),
        ('dcim', '0077_devicelicense'),
        ('configuration', '0016_auto_20190424_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGPNeighbor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('asn', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4294967296)])),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.Interface')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipam.IPAddress')),
            ],
            options={
                'verbose_name': 'BGP Neighbor',
            },
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='interface_a',
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='interface_a_as',
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='interface_b',
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='interface_b_as',
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='interfaces',
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='remote_as',
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='neighbor_a',
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='neighbor_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbors_a', to='configuration.BGPNeighbor'),
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='neighbor_b',
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='neighbor_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbors_b', to='configuration.BGPNeighbor'),
        ),
    ]
