# Generated by Django 2.1.4 on 2019-04-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0017_auto_20190426_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('configuration', models.TextField()),
            ],
            options={
                'verbose_name': 'Routemap',
            },
        ),
    ]
