# Generated by Django 2.1.4 on 2019-04-30 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0019_routemap_neighbors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgpneighbor',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbors', to='dcim.Interface'),
        ),
        migrations.AlterField(
            model_name='bgpsession',
            name='neighbor_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_a', to='configuration.BGPNeighbor'),
        ),
        migrations.AlterField(
            model_name='bgpsession',
            name='neighbor_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_b', to='configuration.BGPNeighbor'),
        ),
    ]
