# Generated by Django 2.1.4 on 2019-05-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0021_auto_20190430_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routemap',
            name='neighbors',
        ),
        migrations.AddField(
            model_name='routemap',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='routemaps', to='configuration.BGPSession'),
        ),
        migrations.AlterField(
            model_name='bgpcommunity',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
