# Generated by Django 2.1.4 on 2019-05-07 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0022_auto_20190507_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgpneighbor',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbors', to='dcim.Interface'),
        ),
    ]
