# Generated by Django 2.1.4 on 2019-05-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0023_auto_20190507_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routemap',
            name='sessions',
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='routemaps_in',
            field=models.ManyToManyField(blank=True, related_name='sessions_in', to='configuration.RouteMap'),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='routemaps_out',
            field=models.ManyToManyField(blank=True, related_name='sessions_out', to='configuration.RouteMap'),
        ),
    ]
