# Generated by Django 2.1.4 on 2019-05-08 10:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0029_vrf_imports'),
        ('configuration', '0024_auto_20190508_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGPASN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('asn', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4294967296)])),
                ('networks', models.ManyToManyField(blank=True, related_name='sessions', to='ipam.Prefix')),
            ],
            options={
                'verbose_name': 'BGP ASN',
            },
        ),
        migrations.AlterField(
            model_name='bgpneighbor',
            name='asn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbors', to='configuration.BGPASN'),
        ),
    ]
