# Generated by Django 2.1.4 on 2019-05-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0026_bgpasn_redistribute_connected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgpneighbor',
            name='asn',
        ),
        migrations.RemoveField(
            model_name='bgpneighbor',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='bgpneighbor',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='communities',
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='neighbor_a',
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='neighbor_b',
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='routemaps_in',
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='routemaps_out',
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='vrf',
        ),
        migrations.DeleteModel(
            name='BGPNeighbor',
        ),
        migrations.DeleteModel(
            name='BGPSession',
        ),
    ]
