# Generated by Django 2.1.4 on 2019-05-22 08:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0029_vrf_imports'),
        ('dcim', '0077_devicelicense'),
        ('configuration', '0027_auto_20190515_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGPDeviceASN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('redistribute_connected', models.BooleanField(default=False)),
                ('additional_prefixes', models.ManyToManyField(blank=True, related_name='additional_prefixes', to='ipam.Prefix')),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.BGPASN')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asns', to='dcim.Device')),
                ('excluded_prefixes', models.ManyToManyField(blank=True, related_name='disabled_prefixes', to='ipam.Prefix')),
            ],
            options={
                'verbose_name': 'Device ASN link',
            },
        ),
        migrations.CreateModel(
            name='BGPNeighbor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('neighbor_type', models.CharField(max_length=50)),
                ('external_neighbor', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('remote_asn', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4294967296)])),
                ('deviceasn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.BGPDeviceASN')),
                ('internal_neighbor_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbors', to='dcim.Device')),
                ('internal_neighbor_ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipam.IPAddress')),
                ('routemaps_in', models.ManyToManyField(blank=True, related_name='sessions_in', to='configuration.RouteMap')),
                ('routemaps_out', models.ManyToManyField(blank=True, related_name='sessions_out', to='configuration.RouteMap')),
            ],
            options={
                'verbose_name': 'BGP Neighbor',
            },
        ),
    ]
