# Generated by Django 2.1.4 on 2019-05-22 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0077_devicelicense'),
        ('configuration', '0028_bgpdeviceasn_bgpneighbor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgpasn',
            name='devices',
            field=models.ManyToManyField(related_name='asns', through='configuration.BGPDeviceASN', to='dcim.Device'),
        ),
        migrations.AlterField(
            model_name='bgpdeviceasn',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcim.Device'),
        ),
    ]
