# Generated by Django 2.1.4 on 2019-05-29 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0077_devicelicense'),
        ('configuration', '0029_auto_20190522_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgpneighbor',
            name='source_interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dcim.Interface'),
        ),
        migrations.AlterField(
            model_name='bgpneighbor',
            name='deviceasn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbors', to='configuration.BGPDeviceASN'),
        ),
    ]
