# Generated by Django 2.1.4 on 2019-06-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0030_auto_20190529_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgpneighbor',
            name='next_hop_self',
            field=models.BooleanField(default=False),
        ),
    ]
