# Generated by Django 2.1.4 on 2019-06-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0031_bgpneighbor_next_hop_self'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgpneighbor',
            name='remove_private_as',
            field=models.BooleanField(default=False),
        ),
    ]
