# Generated by Django 2.1.4 on 2019-06-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0032_bgpneighbor_remove_private_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgpneighbor',
            name='send_community',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
