# Generated by Django 2.1.4 on 2019-06-05 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0033_bgpneighbor_send_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgpneighbor',
            name='routemaps_in',
        ),
        migrations.RemoveField(
            model_name='bgpneighbor',
            name='routemaps_out',
        ),
        migrations.AddField(
            model_name='bgpneighbor',
            name='routemap_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions_in', to='configuration.RouteMap'),
        ),
        migrations.AddField(
            model_name='bgpneighbor',
            name='routemap_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions_out', to='configuration.RouteMap'),
        ),
    ]
