# Generated by Django 2.1.4 on 2019-06-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0034_auto_20190605_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgpneighbor',
            name='soft_reconfiguration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
