# Generated by Django 2.1.4 on 2019-06-07 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0035_bgpneighbor_soft_reconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGPCommunityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BGPCommunityListMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.BGPCommunity')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.BGPCommunityList')),
            ],
        ),
        migrations.AddField(
            model_name='bgpcommunitylist',
            name='communities',
            field=models.ManyToManyField(through='configuration.BGPCommunityListMember', to='configuration.BGPCommunity'),
        ),
    ]
