# Generated by Django 2.1.4 on 2019-08-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0036_auto_20190607_0820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bgpcommunitylist',
            options={'verbose_name': 'BGP Community List'},
        ),
        migrations.AlterField(
            model_name='bgpcommunitylist',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='bgpneighbor',
            name='send_community',
            field=models.CharField(blank=True, default='both', max_length=50, null=True),
        ),
    ]
