# Generated by Django 2.2.6 on 2019-11-13 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0082_auto_20191113_0859'),
        ('virtualization', '0009_custom_tag_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='platform_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_machines', to='dcim.PlatformVersion'),
        ),
    ]
