# Generated by Django 3.0.5 on 2020-04-16 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0010_virtualmachine_platform_version'),
        ('virtualization', '0014_standardize_description'),
    ]

    operations = [
    ]
