# Generated by Django 3.0.5 on 2020-06-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0015_merge_20200416_0717'),
        ('dcim', '0106_flatten_platform_versions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualmachine',
            name='platform_version',
        ),
    ]
