# Generated by Django 3.1 on 2020-12-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0017_update_jsonfield'),
        ('virtualization', '0016_remove_virtualmachine_platform_version'),
    ]

    operations = [
    ]
