# Generated by Django 3.1 on 2020-12-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0018_merge_20201209_1143'),
        ('virtualization', '0019_standardize_name_length'),
    ]

    operations = [
    ]
