# Generated by Django 2.1.4 on 2019-01-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0068_rack_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='clag_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
