# Generated by Django 2.1.4 on 2019-02-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0024_auto_20190122_0747'),
        ('dcim', '0069_interface_clag_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='vxlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interfaces', to='ipam.VLAN'),
        ),
    ]
