# Generated by Django 2.1.4 on 2019-02-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0074_auto_20190213_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='vxlan',
        ),
    ]
