# Generated by Django 2.1.4 on 2019-04-17 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0076_interface_overlay_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('license', models.FileField(upload_to='')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='dcim.Device')),
            ],
        ),
    ]
