# Generated by Django 2.1.4 on 2019-07-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0078_platform_vagrant_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='vagrant_box_version',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
