# Generated by Django 2.1.4 on 2019-08-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0079_platform_vagrant_box_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='vagrant_box',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='vagrant_box_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
