# Generated by Django 2.2.6 on 2019-10-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0075_cable_devices'),
        ('dcim', '0080_vagrant_optional_fields'),
    ]

    operations = [
    ]
