# Generated by Django 2.2.6 on 2019-11-13 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0081_merge_20191002_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='dcim.Platform')),
            ],
            options={
                'unique_together': {('name', 'platform')},
            },
        ),
        migrations.AddField(
            model_name='device',
            name='platform_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='dcim.PlatformVersion'),
        ),
    ]
