# Generated by Django 2.2.6 on 2019-10-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0081_merge_20191002_1555'),
        ('dcim', '0081_merge_20191002_1308'),
    ]

    operations = [
    ]
