# Generated by Django 2.2.8 on 2020-01-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0082_auto_20191113_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformversion',
            options={'ordering': ['platform', 'name']},
        ),
    ]
