# Generated by Django 2.2.6 on 2019-11-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0083_platformversion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='platformversion',
            unique_together={('name', 'platform')},
        ),
    ]
