# Generated by Django 2.2.6 on 2019-11-13 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0084_auto_20191112_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='platform_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='dcim.PlatformVersion'),
        ),
    ]
