# Generated by Django 3.0.5 on 2020-04-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0104_correct_infiniband_types'),
        ('dcim', '0083_auto_20200103_0842'),
    ]

    operations = [
    ]
