# Generated by Django 3.0.5 on 2020-06-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0107_auto_20200605_1233'),
        ('dcim', '0106_role_default_color'),
    ]

    operations = [
    ]
