# Generated by Django 3.0.5 on 2020-06-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0108_merge_20200615_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='version',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='platform',
            unique_together={('name', 'version')},
        ),
    ]
