# Generated by Django 3.0.5 on 2020-06-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0108_merge_20200615_1103'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together={('device', 'name'), ('device', 'clag_id')},
        ),
    ]
