# Generated by Django 3.0.5 on 2020-06-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0109_auto_20200622_0946'),
        ('dcim', '0109_auto_20200623_1048'),
    ]

    operations = [
    ]
