# Generated by Django 3.1 on 2020-12-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0110_merge_20200624_1031'),
        ('dcim', '0116_rearport_max_positions'),
    ]

    operations = [
    ]
