# Generated by Django 3.1 on 2020-12-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0118_delete_devicelicense'),
        ('dcim', '0122_standardize_name_length'),
    ]

    operations = [
    ]
