# Generated by Django 2.1.4 on 2019-03-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0016_exporttemplate_add_cable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='obj_type',
            field=models.ManyToManyField(limit_choices_to={'model__in': ('provider', 'circuit', 'site', 'rack', 'devicetype', 'device', 'interface', 'aggregate', 'prefix', 'ipaddress', 'vlan', 'vrf', 'service', 'secret', 'tenant', 'cluster', 'virtualmachine')}, related_name='custom_fields', to='contenttypes.ContentType'),
        ),
    ]
