# Generated by Django 3.0.11 on 2020-12-01 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0038_auto_20201012_0822'),
        ('extras', '0042_customfield_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectchange',
            name='change_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='object_changes', to='change.ChangeSet'),
        ),
    ]
