# Generated by Django 3.1 on 2020-12-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0047_tag_ordering'),
        ('extras', '0043_objectchange_change_set'),
    ]

    operations = [
    ]
