# Generated by Django 3.1 on 2020-12-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0053_rename_webhook_obj_type'),
        ('extras', '0048_merge_20201209_1143'),
    ]

    operations = [
    ]
