# Generated by Django 2.1.4 on 2019-01-30 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0007_auto_20190125_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='vxlan_prefix',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1677)]),
        ),
    ]
