# Generated by Django 2.1.4 on 2019-02-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0008_auto_20190130_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='vxlan_prefix',
        ),
    ]
