# Generated by Django 2.2.6 on 2019-10-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0009_remove_tenant_vxlan_prefix'),
        ('tenancy', '0006_custom_tag_models'),
    ]

    operations = [
    ]
