# Generated by Django 3.0.5 on 2020-04-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0010_merge_20191002_1555'),
        ('tenancy', '0009_standardize_description'),
    ]

    operations = [
    ]
