# Generated by Django 3.1 on 2020-12-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0011_standardize_name_length'),
        ('tenancy', '0011_merge_20200416_0718'),
    ]

    operations = [
    ]
